SELECT LAST_NAME AS APELLIDO, HIRE_DATE AS FECHA, 
TO_CHAR(NEXT_DAY(ADD_MONTHS(HIRE_DATE, 6), 'LUNES'), 
'FMDAY, "THE" DDSPTH "OF" MONTH, YYYY')
AS REVIEW 
FROM EMPLOYEES; 

SELECT LAST_NAME AS APELLIDO, HIRE_DATE AS FECHA,
TO_CHAR(HIRE_DATE, 'DAY')DAY
FROM EMPLOYEES
ORDER BY TO_CHAR(HIRE_DATE, 'D'); 

SELECT LAST_NAME AS APELLIDO, 
NVL(TO_CHAR(COMMISSION_PCT), 'SIN_COMISION') 
AS COMM
FROM EMPLOYEES;

SELECT (LAST_NAME || ' ' || LPAD(' ', SALARY/
1000 + 1, '*')) AS EMPLOYEES_AND_THEIR_SALARIES
FROM EMPLOYEES
ORDER BY SALARY DESC; 

SELECT 
DECODE(JOB_ID, 'AD_PRES', 'A',
'ST_MAN', 'B', 'IT_PROG', 'C', 
'SA_REP', 'D', 'ST_CELRK', 'E', 'F')AS 
GRADO 
FROM EMPLOYEES; 

SELECT CASE JOB_ID 
WHEN 'AD_PRES' THEN 'A'
WHEN 'ST_MAN' THEN 'B'
WHEN 'IT_PROG' THEN  'C'
WHEN 'SA_REP' THEN 'D'
WHEN 'ST_CELRK' THEN 'E'
ELSE 'F'
END AS GRADO
FROM EMPLOYEES; 
