SELECT JOB_ID, SUM(SALARY) AS SUM_SALARIO
FROM EMPLOYEES 
WHERE JOB_ID  NOT LIKE '%REP'
GROUP BY JOB_ID 
HAVING SUM (SALARY)>13000
ORDER BY SUM (SALARY); 

SELECT MAX(SALARY) AS MAX_SALARIOS 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID; 

SELECT DEPARTMENT_ID AS NUM_DEPARTAMENTO, 
MIN(HIRE_DATE) AS MIN_FECHA
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID
ORDER BY MIN (HIRE_DATE); 

SELECT DEPARTMENT_ID AS DEPARTAMENTO, 
MIN(SALARY) AS MIN_SALARIO
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID
ORDER BY MIN(SALARY); 

SELECT DEPARTMENT_ID AS NUM_DEPARTAMENTO, 
ROUND(AVG(NVL(COMMISSION_PCT, 0))*100, 2) AS "COMM %" 
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT COUNT(JOB_ID)
FROM EMPLOYEES
WHERE JOB_ID LIKE 'IT_PROG'
OR JOB_ID LIKE  'SA_REP'
GROUP BY JOB_ID; 

SELECT DEPARTMENT_ID, 
MIN(SALARY) 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MIN (SALARY) <3000;

SELECT DEPARTMENT_ID AS NUM_DEPARTAMENTO, 
MIN(TO_CHAR(SALARY, '$99,999.00'))
AS MIN_SALARIO
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;